"""add product

Revision ID: 430cea142ca7
Revises: ce6c90e39bad
Create Date: 2023-11-26 01:36:59.154479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '430cea142ca7'
down_revision: Union[str, None] = 'ce6c90e39bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('CategoriesProduct',
    sa.Column('product', sa.Integer(), nullable=False),
    sa.Column('categories', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categories'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product', 'categories')
    )
    op.create_unique_constraint(None, 'categories', ['code'])
    op.create_unique_constraint(None, 'categories', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_table('CategoriesProduct')
    op.drop_table('product')
    # ### end Alembic commands ###
